function [fig, ax] = de_statebins(T, options)
%DE_STATEBINS  Tile-grid choropleth — thin wrapper around de_geobins.
%   Default grid: 'us-states'.  Drop a JSON in data/grids/ and pass its name
%   as Grid to use any other region.
%
%   Usage
%   ─────
%   de_statebins(T, 'StateCol','State', 'ColorCol','Rate')
%   de_statebins(T, 'StateCol','Prov', 'ColorCol','Value', 'Grid','ca-provinces')
%
%   See de_geobins for full documentation.

arguments
    T (:,:) table
    options.StateCol         (1,1) string  = ""
    options.ColorCol         (1,1) string  = ""
    options.TimeCol          (1,1) string  = ""
    options.Title            (1,1) string  = ""
    options.Colormap                       = 'parula'
    options.Grid                           = 'us-states'
    options.ShowTerritories  (1,1) logical = false
    options.Aliases                        = []
    options.CellRenderer     (1,1) string  = "color"
    options.CatCol           (1,1) string  = ""
    options.TopK             (1,1) double  = 5
    options.SharedYLim       (1,2) double  = [NaN NaN]
    options.CatColors                      = []
    options.XCol             (1,1) string  = ""
    options.YCol             (1,1) string  = ""
    options.SharedXLim       (1,2) double  = [NaN NaN]
    options.CLim             (1,2) double  = [NaN NaN]
end

[fig, ax] = de_geobins(T, ...
    'GeoCol',          options.StateCol, ...
    'ColorCol',        options.ColorCol, ...
    'TimeCol',         options.TimeCol, ...
    'Title',           options.Title, ...
    'Colormap',        options.Colormap, ...
    'Grid',            options.Grid, ...
    'ShowTerritories', options.ShowTerritories, ...
    'Aliases',         options.Aliases, ...
    'CellRenderer',    options.CellRenderer, ...
    'CatCol',          options.CatCol, ...
    'TopK',            options.TopK, ...
    'SharedYLim',      options.SharedYLim, ...
    'CatColors',       options.CatColors, ...
    'XCol',            options.XCol, ...
    'YCol',            options.YCol, ...
    'SharedXLim',      options.SharedXLim, ...
    'CLim',            options.CLim);
end
