function [fig, ax] = de_statebins(T, options)
%DE_STATEBINS  Tile-grid choropleth — thin wrapper around de_geobins.
%   Default grid: 'us-states'.  Drop a JSON in data/grids/ and pass its name
%   as Grid to use any other region.
%
%   Usage
%   ─────
%   de_statebins(T, 'StateCol','State', 'ColorVariable','Rate')
%   de_statebins(T, 'StateCol','Prov', 'ColorVariable','Value', 'Grid','ca-provinces')
%
%   See de_geobins for full documentation.

arguments
    T (:,:) table
    options.StateCol         (1,1) string  = ""
    options.ColorVariable         (1,1) string  = ""
    options.TimeCol          (1,1) string  = ""
    options.Title            (1,1) string  = ""
    options.Colormap                       = 'parula'
    options.Grid                           = 'us-states'
    options.ShowTerritories  (1,1) logical = false
    options.Aliases                        = []
    options.CellRenderer     (1,1) string  = "color"
    options.GroupVariable           (1,1) string  = ""
    options.TopK             (1,1) double  = 5
    options.SharedYLim       (1,2) double  = [NaN NaN]
    options.GroupColors                      = []
    options.XCol             (1,1) string  = ""
    options.YCol             (1,1) string  = ""
    options.SharedXLim       (1,2) double  = [NaN NaN]
    options.CLim             (1,2) double  = [NaN NaN]
    options.DataVariables        (1,:) string  = string([])
    options.LegendNote       (1,1) string  = ""
    options.ConfoundNote     (1,1) string  = ""
    options.Scale            (1,1) string  = "auto"
    options.ColorMethod      (1,1) string  = "mean"
end

[fig, ax] = de_geobins(T, ...
    'GeoCol',          options.StateCol, ...
    'ColorVariable',        options.ColorVariable, ...
    'TimeCol',         options.TimeCol, ...
    'Title',           options.Title, ...
    'Colormap',        options.Colormap, ...
    'Grid',            options.Grid, ...
    'ShowTerritories', options.ShowTerritories, ...
    'Aliases',         options.Aliases, ...
    'CellRenderer',    options.CellRenderer, ...
    'GroupVariable',          options.GroupVariable, ...
    'TopK',            options.TopK, ...
    'SharedYLim',      options.SharedYLim, ...
    'GroupColors',       options.GroupColors, ...
    'XCol',            options.XCol, ...
    'YCol',            options.YCol, ...
    'SharedXLim',      options.SharedXLim, ...
    'CLim',            options.CLim, ...
    'DataVariables',       options.DataVariables, ...
    'LegendNote',      options.LegendNote, ...
    'ConfoundNote',    options.ConfoundNote, ...
    'Scale',           options.Scale, ...
    'ColorMethod',     options.ColorMethod);
end
