%{ 
T = SampleData("examples/State_Tobacco_Related_Disparities_Dashboard_Data.csv"); 
T.FromTo = strcat(string(T.Comparing_FocusGroup_), " vs. ", string(T.To_ReferenceGroup_)); 
removevars(T, ["Comparing_FocusGroup_", "To_ReferenceGroup_"]);
DataExplorer(T);
%}

% T = DataExplorer("examples/2026_daygenbyfuel.xlsx", Sheet=2);

% DataExplorer("examples/ncdd-202501-grd-scaled.nc");
T = StrideSample('examples/ncdd-202501-grd-scaled.nc', Variable='tmax', Verbose=false);
T.tmin = StrideSample('examples/ncdd-202501-grd-scaled.nc', Variable='tmin', Verbose=false).tmin;
T.tavg = StrideSample('examples/ncdd-202501-grd-scaled.nc', Variable='tavg', Verbose=false).tavg;
% Aggregate by grid cell: mean and std across all time steps
T_agg = groupsummary(T, {'longitude','latitude'}, {'mean','std'}, {'tmax','tmin','tavg'});
% Geo scatter per variable: color = temporal mean, size = temporal std
de_geoscatter(T_agg.longitude, T_agg.latitude, T_agg.mean_tmax, T_agg.std_tmax, ...
    ColorLabel='mean(tmax)', SizeLabel='std(tmax)', MinSize=5, MaxSize=150, ...
    ColorLim=[-15, 25], SizeLim=[0, 20], ...
    Title='tmax', Source='Climate Data January 2025');
de_geoscatter(T_agg.longitude, T_agg.latitude, T_agg.mean_tmin, T_agg.std_tmin, ...
    ColorLabel='mean(tmin)', SizeLabel='std(tmin)', MinSize=5, MaxSize=150, ...
    ColorLim=[-15, 25], SizeLim=[0, 20], ...
    Title='tmin', Source='Climate Data January 2025');
de_geoscatter(T_agg.longitude, T_agg.latitude, T_agg.mean_tavg, T_agg.std_tavg, ...
    ColorLabel='mean(tavg)', SizeLabel='std(tavg)', MinSize=5, MaxSize=150, ...
    ColorLim=[-15, 25], SizeLim=[0, 20], ...
    Title='tavg', Source='Climate Data January 2025');
